# Generated by Django 3.2 on 2022-08-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='usuario/user-default.png', upload_to='usuario'),
        ),
    ]
